[
    afghanistan, grenada, panama, albania, grenadines, papuanewguinea,
    algeria, guatemala, paraguay,
    andorra, guineabissau,
    peru,
    angola, guineal, philippines,
    antiguabarbuda,
    guyana, poland,
    argentina, haiti, portugal,
    armenia, honduras, puertorico,
    australia, hong_kong, qatar,
    austria, hungary, rawanda,
    azerbaijan, iceland, register,
    bahamas, india, romania,
    bahrain, indonesia, russia,
    bangladesh, iran, sao_tome,
    barbados, iraq, saudiarabia,
    belarus, ireland, senegal,
    belgium, israel, serbia,
    belize, italy, seychelles,
    benin, ivorycoast, sierraleone,
    bhutan, jamaica, singapore,
    bolivia, japan, slovakia,
    bosnia_herzegovina,
    jordan, slovenia,
    botswana, kazakhstan, solomon_islands,
    brazil, kenya, somalia,
    brunei, kiribati, south_korea,
    bulgaria, kuwait, southafrica,
    burkinafaso, kyrgyzstan, spain,
    burma, laos, srilanka,
    burund, latvia, stkitts_nevis,
    cambodia, lebanon, stlucia,
    cameroon, liberia, sudan,
    canada, libya, suriname,
    centralafricanrep,
    liechtenstein,
    sweden,
    chad, lithuania, switzerland,
    chile, luxembourg, syria,
    china, macadonia, taiwan,
    columbia, macau, tajikistan,
    comoros, madagascar, tanzania,
    congo, malawi, thailand,
    costarica, malaysia, togo,
    croatia, maldives, tonga,
    cuba, mali, trinidadandtobago,
    cyprus, malta, tunisia,
    czechrepublic,
    mauritania, turkey,
    demrepcongo, mauritius, turkmenistan,
    denmark, mexico, tuvala,
    djiboutil, micronesia, uae,
    dominica, moldova, uganda,
    dominicanrep,
    monaco, ukraine,
    ecuador, mongolia, united_kingdom,
    egypt, morocco, united_states,
    elsalvado, mozambique, uruguay,
    eq_guinea, namibia, ussr,
    eritrea, nauru, uzbekistan,
    estonia, nepal, vanuatu,
    ethiopia, neth_antilles,
    venezuela,
    fiji, netherlands, vietnam,
    finland, newzealand, western_samoa,
    france, nicaragua, yemen,
    gabon, niger, yugoslavia,
    gambia, nigeria, zaire,
    georgia, north_korea, zambia,
    germany, norway
]
